version: '3'

services:
  scraper-db:
    image: samagragovernance/postgres:latest-pg15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB={POSTGRES_DB}
    ports:
      - 5400:5432
