version: '3'

services:
  db:
    image: samagragovernance/postgres:latest-pg15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB={POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build: 
      context: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}

volumes:
  db:
